- hosts: cen
  gather_facts: 0
  tasks:
    - file:
        path: /tmp/new_book
        state: directory
        mode: 0777
    - copy:
        src: /etc/fstab
        dest: /tmp/new_book
    - yum:
        name: vsftpd 
        state: installed
    - service:
        name: vsftpd 
        state: started
